### ISSUE TITLE
Is LogSeer or LogAgent opensource?

### ISSUE THREAD

**Issue by LronDC** [kubecube-io/kubecube-installer#41]

**Comment by zhujf1989** [comment]
在我们的路标中，日志服务及日志采集端会使用我们自研且开源的Loggie，因此KubeCube现有版本中使用的LogSeer及LogAgent不会开源了，在KubeCube未来版本中会直接使用Loggie。目前Loggie已经开源，https://github.com/loggie-io/loggie。

**Comment by zhangyeda** [comment]
Loggie开源了，但是LogSeer 2.3.0 还会不会开源？如果不开源的话可否提供arm64镜像？

**Comment by zhangyeda** [comment]
Loggie开源了，但是LogSeer 2.3.0 还会不会开源？如果不开源的话可否提供arm64镜像？> 在我们的路标中，日志服务及日志采集端会使用我们自研且开源的Loggie，因此KubeCube现有版本中使用的LogSeer及LogAgent不会开源了，在KubeCube未来版本中会直接使用Loggie。目前Loggie已经开源，[https://github.com/loggie-io/loggie。](https://github.com/loggie-io/loggie%E3%80%82)
